name: ArgoCD App

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update GitOps deployment repo
        run: |
          # Güncel image tag'ini yaz
          sed -i "s|tag: .*|tag: \"${{ github.sha }}\"|g" values.yaml 
          
          # Git commit ve push işlemleri
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push origin main